### PR TITLE
Order Summary Unified Organism

### PR DESCRIPTION
**Pull request by minabadrous**

### CODE REVIEW

**Review by KenwayTheGreat — APPROVED** [review]
Tested it locally and all is good

**Comment by frontastic-developers** [comment]
## :white_check_mark: Tests [2023.06.20.11.42-test](https://thegoodstore.frontastic.io/developer/continuousIntegration?build=2023.06.20.11.42-test&branch=order-summary) on branch [`order-summary`](https://github.com/frontastic-developers/customer-thegoodstore/tree/order-summary) successful

Commit [`87ba7965`](https://github.com/frontastic-developers/customer-thegoodstore/commit/87ba79655a11817d33c99eb5972feeed4e42a252) by *minabadrous* in 1:42

**Comment by frontastic-developers** [comment]
## :white_check_mark: Tests [2023.06.21.08.37-test](https://thegoodstore.frontastic.io/developer/continuousIntegration?build=2023.06.21.08.37-test&branch=order-summary) on branch [`order-summary`](https://github.com/frontastic-developers/customer-thegoodstore/tree/order-summary) successful

Commit [`d76accaa`](https://github.com/frontastic-developers/customer-thegoodstore/commit/d76accaa623f4c5b8507b62cd5a7c1fa538601f5) by *minabadrous* in 1:48

**Comment by frontastic-developers** [comment]
## :white_check_mark: Tests [2023.06.26.11.58-test](https://thegoodstore.frontastic.io/developer/continuousIntegration?build=2023.06.26.11.58-test&branch=order-summary) on branch [`order-summary`](https://github.com/frontastic-developers/customer-thegoodstore/tree/order-summary) successful

Commit [`ee0d860d`](https://github.com/frontastic-developers/customer-thegoodstore/commit/ee0d860d5f6d21d92e150d8d7210599185d037f8) by *minabadrous* in 1:34

**Pull request merged**
