### PR TITLE
FP-4512: Types updates

### PR DESCRIPTION
**Pull request by KenwayTheGreat**
- Removed frontend-domain-types
- Added ct-types folder
- Updated the imports for the frontend

### CODE REVIEW

**Comment by frontastic-developers** [comment]
## :white_check_mark: Tests [2023.06.13.11.23-test](https://thegoodstore.frontastic.io/developer/continuousIntegration?build=2023.06.13.11.23-test&branch=FP-4512-the-good-store-frontend-domain-types) on branch [`FP-4512-the-good-store-frontend-domain-types`](https://github.com/frontastic-developers/customer-thegoodstore/tree/FP-4512-the-good-store-frontend-domain-types) successful

Commit [`2d17da81`](https://github.com/frontastic-developers/customer-thegoodstore/commit/2d17da81f979f94683a67d150ee59e339ae14d23) by *KenwayTheGreat* in 1:45

**Review by xcintas — APPROVED** [review]

**Comment by frontastic-developers** [comment]
## :white_check_mark: Tests [2023.06.14.09.55-test](https://thegoodstore.frontastic.io/developer/continuousIntegration?build=2023.06.14.09.55-test&branch=FP-4512-the-good-store-frontend-domain-types) on branch [`FP-4512-the-good-store-frontend-domain-types`](https://github.com/frontastic-developers/customer-thegoodstore/tree/FP-4512-the-good-store-frontend-domain-types) successful

Commit [`33fc2278`](https://github.com/frontastic-developers/customer-thegoodstore/commit/33fc2278b1d01782d3e4754f0d5f9714618607eb) by *KenwayTheGreat* in 1:56

**Review by xcintas — APPROVED** [review]

**Comment by frontastic-developers** [comment]
## :white_check_mark: Tests [2023.06.20.08.28-test](https://thegoodstore.frontastic.io/developer/continuousIntegration?build=2023.06.20.08.28-test&branch=FP-4512-the-good-store-frontend-domain-types) on branch [`FP-4512-the-good-store-frontend-domain-types`](https://github.com/frontastic-developers/customer-thegoodstore/tree/FP-4512-the-good-store-frontend-domain-types) successful

Commit [`a6358a9e`](https://github.com/frontastic-developers/customer-thegoodstore/commit/a6358a9e6ef27d0064cd94485f19850c924fda8d) by *KenwayTheGreat* in 1:47

**Review by abdotaker608 — APPROVED** [review]

**Comment by frontastic-developers** [comment]
## :white_check_mark: Tests [2023.06.20.09.21-test](https://thegoodstore.frontastic.io/developer/continuousIntegration?build=2023.06.20.09.21-test&branch=FP-4512-the-good-store-frontend-domain-types) on branch [`FP-4512-the-good-store-frontend-domain-types`](https://github.com/frontastic-developers/customer-thegoodstore/tree/FP-4512-the-good-store-frontend-domain-types) successful

Commit [`cf1ea2bd`](https://github.com/frontastic-developers/customer-thegoodstore/commit/cf1ea2bd5226e0d625c9b7465582fad04736325c) by *KenwayTheGreat* in 1:53

**Pull request merged**
