### PR TITLE
fix(FP-4202): pass currency in query

### PR DESCRIPTION
**Pull request by femi-abejide**
Allow currency to be passed in as query parameter
image

JIRA: https://frontastic.atlassian.net/browse/FP-4202

### CODE REVIEW

**Comment by frontastic-developers** [comment]
## :white_check_mark: Tests [2023.05.23.08.02-test](https://thegoodstore.frontastic.io/developer/continuousIntegration?build=2023.05.23.08.02-test&branch=fix/FP-4202-remove-currency-from-API-HUB-locale) on branch [`fix/FP-4202-remove-currency-from-API-HUB-locale`](https://github.com/frontastic-developers/customer-thegoodstore/tree/fix/FP-4202-remove-currency-from-API-HUB-locale) successful

Commit [`9d6bf8ce`](https://github.com/frontastic-developers/customer-thegoodstore/commit/9d6bf8ce6fc17d6110812db2e6da715d3a2c6432) by *femi-abejide* in 2:05

**Comment by frontastic-developers** [comment]
## :white_check_mark: Tests [2023.05.23.12.04-test](https://thegoodstore.frontastic.io/developer/continuousIntegration?build=2023.05.23.12.04-test&branch=fix/FP-4202-remove-currency-from-API-HUB-locale) on branch [`fix/FP-4202-remove-currency-from-API-HUB-locale`](https://github.com/frontastic-developers/customer-thegoodstore/tree/fix/FP-4202-remove-currency-from-API-HUB-locale) successful

Commit [`3c7a2b67`](https://github.com/frontastic-developers/customer-thegoodstore/commit/3c7a2b67d3568ed3bbd338cf57298fb9c08550be) by *femi-abejide* in 2:04

**Comment by frontastic-developers** [comment]
## :white_check_mark: Tests [2023.05.24.10.17-test](https://thegoodstore.frontastic.io/developer/continuousIntegration?build=2023.05.24.10.17-test&branch=fix/FP-4202-remove-currency-from-API-HUB-locale) on branch [`fix/FP-4202-remove-currency-from-API-HUB-locale`](https://github.com/frontastic-developers/customer-thegoodstore/tree/fix/FP-4202-remove-currency-from-API-HUB-locale) successful

Commit [`990cb5d4`](https://github.com/frontastic-developers/customer-thegoodstore/commit/990cb5d4e8fc1aae7567a0ec47eefc2469d45966) by *femi-abejide* in 2:16

**Review by abdotaker608 — APPROVED** [review]

**Comment by frontastic-developers** [comment]
## :white_check_mark: Tests [2023.06.14.10.04-test](https://thegoodstore.frontastic.io/developer/continuousIntegration?build=2023.06.14.10.04-test&branch=fix/FP-4202-remove-currency-from-API-HUB-locale) on branch [`fix/FP-4202-remove-currency-from-API-HUB-locale`](https://github.com/frontastic-developers/customer-thegoodstore/tree/fix/FP-4202-remove-currency-from-API-HUB-locale) successful

Commit [`06ed76da`](https://github.com/frontastic-developers/customer-thegoodstore/commit/06ed76dad4861b3b1c9a3f3829ec99e5f9f3934e) by *femi-abejide* in 1:51

**Review by xcintas — APPROVED** [review]

**Pull request merged**
